### ISSUE TITLE
Illegal hardware access when trying to refactor the first part of this example into functions

### ISSUE THREAD

**Issue by shrit** [ocornut/imgui#6976]
Hello,

I started with this example:
https://github.com/ocornut/imgui/blob/master/examples/example_glfw_opengl3/main.cpp

My idea was to refactor the first two parts, the `glfw` into its own init function and the same for `imgui` however, when I do this, I got an illegal hardware access error from the binary.

In another word, move everything from line 40 to 72 into a function and from 75 to 87 to another function and call them the one after the another as described here. Of course you would need to declare the window pointer at the start and pass it to each one.

https://github.com/ocornut/imgui/blob/88fec097158867edf7753fe0d842d23d67e7966d/examples/example_glfw_opengl3/main.cpp#L40-L87

Is there any specific reason for this ? I do not understand why it is not possible to refactor this.

**Comment by ocornut** [comment]
Hello Omar :)

you probably made a mistake which you are omitting in your description. Please double check things and use a debugger to clarify the error and share it here. Right now you have omitted most of the information we request for opening an issue and we cannot meaningfully help without it.

**Comment by GamingMinds-DanielC** [comment]
It is absolutely possible to refactor this, it just needs to be done correctly. Please show at least your refactored code, otherwise we have no chance to see what's wrong with it.

**Comment by shrit** [comment]
okay good to know, I will try to post the full example with more details before the end of the day (because I need sometime to full all the details), at least I know it is an error on my side, and I did not try to do something impossible

**Comment by shrit** [comment]
Adding more information about the above issue:

Version: v1.89.9 (Obtained from the header file)
Branch: master
Back-ends: glfw opengl3 basic example
Compiler: g++
Operating System: Linux linux-4-102 6.4.7-arch1-3 #1 SMP PREEMPT_DYNAMIC Wed, 02 Aug 2023 09:47:27 +0000 x86_64 GNU/Linux

Here is the refactored example (full main.cpp is in the attachment if necessary [main.txt](https://github.com/ocornut/imgui/files/13250016/main.txt)):

```cpp
int init_glfw(GLFWwindow* window)
{
  glfwSetErrorCallback(glfw_error_callback);
  if (!glfwInit())
      return 1;

  const char* glsl_version = "#version 130";
  glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
  glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 0);

  window = glfwCreateWindow(1280, 720, "Dear ImGui GLFW+OpenGL3 example", nullptr, nullptr);
  glfwMakeContextCurrent(window);
  glfwSwapInterval(1); // Enable vsync
}

void init_imgui(ImGuiIO& io, GLFWwindow* window)
{
  IMGUI_CHECKVERSION();
  ImGui::CreateContext();
  io = ImGui::GetIO(); (void)io;
  io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;     // Enable Keyboard Controls
  io.ConfigFlags |= ImGuiConfigFlags_NavEnableGamepad;      // Enable Gamepad Controls

  // Setup Dear ImGui style
  ImGui::StyleColorsDark();
  //ImGui::StyleColorsLight();

  const char* glsl_version = "#version 130";
  // Setup Platform/Renderer backends
  ImGui_ImplGlfw_InitForOpenGL(window, true);
  ImGui_ImplOpenGL3_Init(glsl_version);
}

// Main code
int main(int, char**)
{
  GLFWwindow* window = nullptr;
  ImGuiIO io;
  init_glfw(window);
  init_imgui(io, window); // Setup Dear ImGui context
  // .
  // .
  //.  The same remaining part of the example ....

```

When running the example:

```
 ./example_glfw_opengl3

[2]    859891 illegal hardware instruction (core dumped)  ./example_glfw_opengl3
```

gdb info

```
(gdb) bt full
#0  0x00005555555587b4 in init_glfw (window=0x5555556e6b00) at main.cpp:46
        glsl_version = 0x55555563301c "#version 130"
#1  0x00005555555588c5 in main () at main.cpp:72
        window = 0x0
        io = {ConfigFlags = 0, BackendFlags = 0, DisplaySize = {x = -1, y = -1}, DeltaTime = 0.0166666675, IniSavingRate = 5, IniFilename = 0x5555556332b0 "imgui.ini", LogFilename = 0x5555556332ba "imgui_log.txt", UserData = 0x0,
          Fonts = 0x0, FontGlobalScale = 1, FontAllowUserScaling = false, FontDefault = 0x0, DisplayFramebufferScale = {x = 1, y = 1}, MouseDrawCursor = false, ConfigMacOSXBehaviors = false, ConfigInputTrickleEventQueue = true,
          ConfigInputTextCursorBlink = true, ConfigInputTextEnterKeepActive = false, ConfigDragClickToInputText = false, ConfigWindowsResizeFromEdges = true, ConfigWindowsMoveFromTitleBarOnly = false, ConfigMemoryCompactTimer = 60,
          MouseDoubleClickTime = 0.300000012, MouseDoubleClickMaxDist = 6, MouseDragThreshold = 6, KeyRepeatDelay = 0.275000006, KeyRepeatRate = 0.0500000007, ConfigDebugBeginReturnValueOnce = false,
          ConfigDebugBeginReturnValueLoop = false, ConfigDebugIgnoreFocusLoss = false, ConfigDebugIniSettings = false, BackendPlatformName = 0x0, BackendRendererName = 0x0, BackendPlatformUserData = 0x0, BackendRendererUserData = 0x0,
          BackendLanguageUserData = 0x0, GetClipboardTextFn = 0x0, SetClipboardTextFn = 0x0, ClipboardUserData = 0x0, SetPlatformImeDataFn = 0x0, ImeWindowHandle = 0x0, PlatformLocaleDecimalPoint = 46, WantCaptureMouse = false,
          WantCaptureKeyboard = false, WantTextInput = false, WantSetMousePos = false, WantSaveIniSettings = false, NavActive = false, NavVisible = false, Framerate = 0, MetricsRenderVertices = 0, MetricsRenderIndices = 0,
          MetricsRenderWindows = 0, MetricsActiveWindows = 0, MetricsActiveAllocations = 0, MouseDelta = {x = 0, y = 0}, KeyMap = {-1 <repeats 652 times>}, KeysDown = {false <repeats 652 times>}, NavInputs = {0 <repeats 16 times>},
          Ctx = 0x0, MousePos = {x = -3.40282347e+38, y = -3.40282347e+38}, MouseDown = {false, false, false, false, false}, MouseWheel = 0, MouseWheelH = 0, MouseSource = ImGuiMouseSource_Mouse, KeyCtrl = false, KeyShift = false,
          KeyAlt = false, KeySuper = false, KeyMods = 0, KeysData = {{Down = false, DownDuration = -1, DownDurationPrev = -1, AnalogValue = 0} <repeats 652 times>}, WantCaptureMouseUnlessPopupClose = false, MousePosPrev = {
            x = -3.40282347e+38, y = -3.40282347e+38}, MouseClickedPos = {{x = 0, y = 0}, {x = 0, y = 0}, {x = 0, y = 0}, {x = 0, y = 0}, {x = 0, y = 0}}, MouseClickedTime = {0, 0, 0, 0, 0}, MouseClicked = {false, false, false, false,
            false}, MouseDoubleClicked = {false, false, false, false, false}, MouseClickedCount = {0, 0, 0, 0, 0}, MouseClickedLastCount = {0, 0, 0, 0, 0}, MouseReleased = {false, false, false, false, false}, MouseDownOwned = {false,
            false, false, false, false}, MouseDownOwnedUnlessPopupClose = {false, false, false, false, false}, MouseWheelRequestAxisSwap = false, MouseDownDuration = {-1, -1, -1, -1, -1}, MouseDownDurationPrev = {-1, -1, -1, -1, -1},
          MouseDragMaxDistanceSqr = {0, 0, 0, 0, 0}, PenPressure = 0, AppFocusLost = false, AppAcceptingEvents = true, BackendUsingLegacyKeyArrays = -1 '\377', BackendUsingLegacyNavInputArray = true, InputQueueSurrogate = 0,
          InputQueueCharacters = {Size = 0, Capacity = 0, Data = 0x0}}
        show_demo_window = false
        show_another_window = false
        clear_color = {x = 0, y = 0, z = 0, w = 0}
(gdb) Quit
```
Let me know if you need anything else, I attached the refactored example as txt, you can pull it change extension and compile it and see if this is also happening on your machine as well.

**Comment by emoon** [comment]
The issue is that ` window = glfwCreateWindow(1280, 720, "Dear ImGui GLFW+OpenGL3 example", nullptr, nullptr);` will only set this variable within the scope of the function. 

When you call `  init_imgui(io, window); // Setup Dear ImGui context` the `window` ptr will still be `null`

**Comment by emoon** [comment]
Just change the code so it looks something like this instead

```C++
  ImGuiIO io;
  GLFWwindow* window = init_glfw();
  ...
```
And return the window ptr from the `init_glfw()` function.

**Comment by shrit** [comment]
Okay thanks, that's resolved the issue.
